### ISSUE TITLE
Why is this happening?

### ISSUE THREAD

**Issue by cola111222** [jannoelc/ro-pixel-bot#1]
![image](https://github.com/jannoelc/ro-pixel-bot/assets/170644149/e6457ea9-46fa-454c-9dda-c0587fdb4acd)
Why is this happening?

**Comment by wandersonlt** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/d32b3833-56a4-4901-89e4-909612e0b551)

**Comment by jannoelc** [comment]
Please see https://github.com/jannoelc/ro-pixel-bot/issues/2

**Comment by jannoelc** [comment]
See #2 for resolution
