### ISSUE TITLE
How to resolve this error

### ISSUE THREAD

**Issue by wandersonlt** [jannoelc/ro-pixel-bot#2]
![image](https://github.com/user-attachments/assets/bd1997f7-61a5-492f-8ee3-2ddf877efa70)

**Comment by jannoelc** [comment]
Can you please try removing ‘n on lines 6 and 7 on this file?

https://github.com/jannoelc/ro-pixel-bot/blob/main/autohotkey.ahk

Were you able to inspect this repository as well?

https://github.com/jannoelc/circuitpy-usbhid-nodejs 

You need a hardware that supports CircuitPython to act as USB HID.

**Comment by jannoelc** [comment]
@wandersonlt you are executing the script incorrectly. You should run the node scripts inside the bot_scripts folder and not the ahk file directly.

The bot scripts will spawn its own ahk process to be used. Make sure nodejs is installed, all dependencies are installed, and the bot_script is run via `node bot_scripts/<script_name>`.

This is a screenshot of the script's interaction with the ahk instance currently running.
![image](https://github.com/user-attachments/assets/1bc40ef9-a096-45cb-8eeb-e994598cce6c)

This project requires you to have a sufficient development background at least, I won't be able to support non-technical people unfortunately.

Closing the issue
